### ISSUE TITLE
Password reset only works as a magic link

### ISSUE THREAD

**Issue by maleksal** [nuxtbase/auth-ui-vue#11]
According to the Supabase documentation on password reset, a redirect URL must be provided for users to be directed to the updated password page after clicking the reset link. However, there's a limitation in the Auth component initialization, as it only accepts a redirecting URL reserved for auth callbacks. 

I think it can be solved by adding a new prop `passwordResetRedirectURL ` for the Auth component that will be supplied as a redirect URL for resetting the password.

https://supabase.com/docs/guides/auth/auth-password-reset
>- Send email for password reset using [.resetPasswordForEmail](https://supabase.com/docs/reference/javascript/auth-resetpasswordforemail) while providing a redirectTo parameter
>- Email link will work as a magic link and log the user in then take them to the url specified in the redirectTo parameter
>- Create form to update the password and call the [.updateUser](https://supabase.com/docs/reference/javascript/auth-updateuser) method with the new password

**Comment by xiaoluoboding** [comment]
checkout v0.3.5
