### ISSUE TITLE
Anonymous user

### ISSUE THREAD

**Issue by CyberCowboy404** [nuxtbase/auth-ui-vue#19]
I've enabled anonymous sign_in, but when I do sign_in/sign_up via this plugin new user created.
Is this supports anonymous users?

**Comment by xiaoluoboding** [comment]
Hello, I have received the PR. I need some time to test it out. It seems to be a new feature added by Supabase.

**Comment by CyberCowboy404** [comment]
> Hello, I have received the PR. I need some time to test it out. It seems to be a new feature added by Supabase.

Sure, tell me if you need some help.
Thanks

**Comment by xiaoluoboding** [comment]
https://github.com/nuxtbase/auth-ui-vue/releases/tag/v0.3.7
